version: '3.8'

services:
  pyler_auth:
    image: auth:latest
    container_name: auth_service
    ports:
      - "8001:8000"
    depends_on:
      pyler_db:
        condition: service_healthy  # 데이터베이스가 준비된 후에 시작
    environment:
      - DATABASE_URL=postgresql://pyler:pyler1!@pyler_db:5432/pyler
      
  # api:
  #   build: ./video_hub/api
  #   container_name: video_hub_api
  #   ports:
  #     - "8000:8000"

  # crawler:
  #   build: ./video_hub/crawler
  #   container_name: video_hub_crawler

  pyler_db:
    image: postgres:latest
    container_name: pyler_db
    environment:
      POSTGRES_USER: pyler
      POSTGRES_PASSWORD: pyler1!
      POSTGRES_DB: pyler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # healthcheck 추가
      test: ["CMD-SHELL", "pg_isready -U pyler"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
